<!DOCTYPE html>
<html>
  <head>
    <title>Homepage</title>
    <link rel="stylesheet" href="gaya.css">
    <script src="tulis.js"></script>
  </head>
  <body>
    <?php include 'navbar.php'; ?>
    <div class="container">
      <?php include 'sidebar.php'; ?>
      <div class="content">
        <h1>Welcome to our Homepage!</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae urna at mauris laoreet faucibus. Sed vel pulvinar lectus, vel ultricies risus. Vestibulum ultricies orci in urna gravida, in euismod elit lacinia. Donec sed urna ac tellus consectetur venenatis. Praesent euismod, augue nec vestibulum gravida, velit mi suscipit tortor, vel semper velit libero quis nunc. Vivamus malesuada justo non risus molestie lobortis. Sed interdum purus libero, ac faucibus felis dapibus vel. Proin dictum ante vel imperdiet vulputate.</p>
        <p>Donec quis lectus nec enim pharetra faucibus quis ac justo. Nullam vel rutrum neque. Nunc dapibus mauris quis purus ultricies lacinia. Aenean aliquam ex vel blandit dictum. Donec sodales semper libero a fermentum. Sed eget justo quis sapien tincidunt molestie. Aenean lobortis mi sed magna consequat blandit. Vivamus porttitor nisi lectus, in pretium lacus elementum eu. Sed ultrices gravida massa, non lacinia mauris tincidunt vel. Suspendisse potenti. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed ullamcorper blandit massa id ullamcorper. Praesent euismod sagittis velit, a vestibulum nisl. Aliquam et mi eget sapien venenatis maximus a ac tellus. Integer et euismod orci, vitae finibus odio.</p>
      </div><div class="content">
        <h1>Welcome to our Homepage!</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae urna at mauris laoreet faucibus. Sed vel pulvinar lectus, vel ultricies risus. Vestibulum ultricies orci in urna gravida, in euismod elit lacinia. Donec sed urna ac tellus consectetur venenatis. Praesent euismod, augue nec vestibulum gravida, velit mi suscipit tortor, vel semper velit libero quis nunc. Vivamus malesuada justo non risus molestie lobortis. Sed interdum purus libero, ac faucibus felis dapibus vel. Proin dictum ante vel imperdiet vulputate.</p>
        <p>Donec quis lectus nec enim pharetra faucibus quis ac justo. Nullam vel rutrum neque. Nunc dapibus mauris quis purus ultricies lacinia. Aenean aliquam ex vel blandit dictum. Donec sodales semper libero a fermentum. Sed eget justo quis sapien tincidunt molestie. Aenean lobortis mi sed magna consequat blandit. Vivamus porttitor nisi lectus, in pretium lacus elementum eu. Sed ultrices gravida massa, non lacinia mauris tincidunt vel. Suspendisse potenti. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed ullamcorper blandit massa id ullamcorper. Praesent euismod sagittis velit, a vestibulum nisl. Aliquam et mi eget sapien venenatis maximus a ac tellus. Integer et euismod orci, vitae finibus odio.</p>
      </div><div class="content">
        <h1>Welcome to our Homepage!</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae urna at mauris laoreet faucibus. Sed vel pulvinar lectus, vel ultricies risus. Vestibulum ultricies orci in urna gravida, in euismod elit lacinia. Donec sed urna ac tellus consectetur venenatis. Praesent euismod, augue nec vestibulum gravida, velit mi suscipit tortor, vel semper velit libero quis nunc. Vivamus malesuada justo non risus molestie lobortis. Sed interdum purus libero, ac faucibus felis dapibus vel. Proin dictum ante vel imperdiet vulputate.</p>
        <p>Donec quis lectus nec enim pharetra faucibus quis ac justo. Nullam vel rutrum neque. Nunc dapibus mauris quis purus ultricies lacinia. Aenean aliquam ex vel blandit dictum. Donec sodales semper libero a fermentum. Sed eget justo quis sapien tincidunt molestie. Aenean lobortis mi sed magna consequat blandit. Vivamus porttitor nisi lectus, in pretium lacus elementum eu. Sed ultrices gravida massa, non lacinia mauris tincidunt vel. Suspendisse potenti. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed ullamcorper blandit massa id ullamcorper. Praesent euismod sagittis velit, a vestibulum nisl. Aliquam et mi eget sapien venenatis maximus a ac tellus. Integer et euismod orci, vitae finibus odio.</p>
      </div><div class="content">
        <h1>Welcome to our Homepage!</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae urna at mauris laoreet faucibus. Sed vel pulvinar lectus, vel ultricies risus. Vestibulum ultricies orci in urna gravida, in euismod elit lacinia. Donec sed urna ac tellus consectetur venenatis. Praesent euismod, augue nec vestibulum gravida, velit mi suscipit tortor, vel semper velit libero quis nunc. Vivamus malesuada justo non risus molestie lobortis. Sed interdum purus libero, ac faucibus felis dapibus vel. Proin dictum ante vel imperdiet vulputate.</p>
        <p>Donec quis lectus nec enim pharetra faucibus quis ac justo. Nullam vel rutrum neque. Nunc dapibus mauris quis purus ultricies lacinia. Aenean aliquam ex vel blandit dictum. Donec sodales semper libero a fermentum. Sed eget justo quis sapien tincidunt molestie. Aenean lobortis mi sed magna consequat blandit. Vivamus porttitor nisi lectus, in pretium lacus elementum eu. Sed ultrices gravida massa, non lacinia mauris tincidunt vel. Suspendisse potenti. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed ullamcorper blandit massa id ullamcorper. Praesent euismod sagittis velit, a vestibulum nisl. Aliquam et mi eget sapien venenatis maximus a ac tellus. Integer et euismod orci, vitae finibus odio.</p>
      </div><div class="content">
        <h1>Welcome to our Homepage!</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae urna at mauris laoreet faucibus. Sed vel pulvinar lectus, vel ultricies risus. Vestibulum ultricies orci in urna gravida, in euismod elit lacinia. Donec sed urna ac tellus consectetur venenatis. Praesent euismod, augue nec vestibulum gravida, velit mi suscipit tortor, vel semper velit libero quis nunc. Vivamus malesuada justo non risus molestie lobortis. Sed interdum purus libero, ac faucibus felis dapibus vel. Proin dictum ante vel imperdiet vulputate.</p>
        <p>Donec quis lectus nec enim pharetra faucibus quis ac justo. Nullam vel rutrum neque. Nunc dapibus mauris quis purus ultricies lacinia. Aenean aliquam ex vel blandit dictum. Donec sodales semper libero a fermentum. Sed eget justo quis sapien tincidunt molestie. Aenean lobortis mi sed magna consequat blandit. Vivamus porttitor nisi lectus, in pretium lacus elementum eu. Sed ultrices gravida massa, non lacinia mauris tincidunt vel. Suspendisse potenti. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed ullamcorper blandit massa id ullamcorper. Praesent euismod sagittis velit, a vestibulum nisl. Aliquam et mi eget sapien venenatis maximus a ac tellus. Integer et euismod orci, vitae finibus odio.</p>
      </div>
    </div>
  </body>
</html>
